#!/bin/sh
### BEGIN INIT INFO
# Provides:          team3223 usb stick
# Required-Start:    
# Required-Stop:     
# Default-Start:     
# Default-Stop:      
# Short-Description: mount a usb stick
# Description:       mount a usb stick for logging structure
#                    sensor data
### END INIT INFO

case "$1" in
	start)
		mount /dev/sda1 /mnt 2>> /root/usb-stick.log
		;;
	stop)
		umount /mnt 2>> /root/usb-stick.log
		;;
esac
